# Copyright (c) 2021-2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Boost the Bluetooth signal only if having connection issues
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# NKRO support
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Prevent using some consumer key codes, but allows compatibility with more host OSes. See: https://zmk.dev/docs/config/system
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# Uncomment the following to enable deep sleep, default timeout is 15min
CONFIG_ZMK_SLEEP=y
# Set deep sleep timeout to 1h
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Set debounce settings (default is 5 for both)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3

# Mouse emulation support and smooth scrolling
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Peripheral preferred min/max connection interval in 1.25ms units. Set 7.5ms-15ms (6-12) BLE polling range.
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
# Aggregate config that enables both CONFIG_ZMK_BLE_EXPERIMENTAL_CONN and CONFIG_ZMK_BLE_EXPERIMENTAL_SEC. See: https://zmk.dev/docs/config/bluetooth. Allows overwrite of keys from prior connection, fixing stale bond issue.
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
# Improve compatibility Windows Bluetooth chipsets. Should also be disabled as part of CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y already
CONFIG_BT_CTLR_PHY_2M=n
# Maximize BT transmit power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Enable passkey entry during pairing for enhanced security
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Dynamic Macro Module Settings
# Set shared storage pool settings. 
## The shared pool is sized at compile time as AVG_EVENTS_PER_SLOT x SLOT_COUNT. 1 keystroke = 2 events.
## AVG is capped at 64, so slot count is the only lever to increase further. 
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_RAM_SLOTS=3
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_AVG_EVENTS_PER_SLOT=64
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_MAX_EVENTS=1024
# Note: By disabling persistent NVS slots, you make NVS_SLOTS setting irrelevant
#CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_PERSIST=y
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_NVS_SLOTS=1
# Only print status for used macro slots, not all allocated ones
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_STATUS_USED=y
# Only show command feedback for errors, don't auto-clear
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_FEEDBACK_ERROR=y
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_FEEDBACK_AUTO_ERASE=n
# Enable custom FI locale implementation
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_LOCALE_FI=y
# Enable custom auto-overwrite behavior
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_AUTO_OVERWRITE_RAM=y
CONFIG_ZMK_BEHAVIOR_DYNAMIC_MACRO_AUTO_OVERWRITE_NVS=y